### ISSUE TITLE
Can't start app with meteor toys installed

### ISSUE THREAD

**Issue by iamjaredwalters** [MeteorToys/allthings#41]
I turned on throttle and attempted to restart my app but was thrown this error:

> TypeError: Property 'undefined' of object [object Object] is not a function W20151001-17:14:37.053(-7)? (STDERR)     at Package (meteor://:computer:app/packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)

Uninstalling Meteortoys is the only way I can get my app to start again.

**Comment by ChaseJ** [comment]
+1. Fix from https://github.com/MeteorToys/allthings/issues/39 worked for a day, now I'm having the same issue.

**Comment by aminecmi** [comment]
+1

**Comment by Anima-t3d** [comment]
+1 even I just updated it 12 hours ago and just actually used it like 30 mins ago, but now without saving it occurred...

**Comment by came** [comment]
+1

**Comment by skeltoras** [comment]
+1 same as the other day.

**Comment by meandkareem** [comment]
+1

**Comment by Siyfion** [comment]
Yup, same thing:

```
W20151002-11:04:54.237(1)? (STDERR) 
W20151002-11:04:54.238(1)? (STDERR) /Users/siyfion/.meteor/packages/meteor-tool/.1.1.9.15zselt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151002-11:04:54.238(1)? (STDERR)                         throw(ex);
W20151002-11:04:54.238(1)? (STDERR)                               ^
W20151002-11:04:54.238(1)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20151002-11:04:54.238(1)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20151002-11:04:54.238(1)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20151002-11:04:54.238(1)? (STDERR)     at /Users/siyfion/Git/LabelLogicLive/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20151002-11:04:54.239(1)? (STDERR)     at /Users/siyfion/Git/LabelLogicLive/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20151002-11:04:54.239(1)? (STDERR)     at /Users/siyfion/Git/LabelLogicLive/.meteor/local/build/programs/server/boot.js:242:10
W20151002-11:04:54.239(1)? (STDERR)     at Array.forEach (native)
W20151002-11:04:54.239(1)? (STDERR)     at Function._.each._.forEach (/Users/siyfion/.meteor/packages/meteor-tool/.1.1.9.15zselt++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151002-11:04:54.239(1)? (STDERR)     at /Users/siyfion/Git/LabelLogicLive/.meteor/local/build/programs/server/boot.js:137:5
```

**Comment by johnschult** [comment]
Same here :frowning:

**Comment by msavin** [comment]
Sorry for the inconvenience, I'm looking into it. It's strange because it works then breaks.

**Comment by agad** [comment]
+1 same thing happening here.  It works for a bit, then a file changes, a hot reload occurs and get the same error.  Running on windows 8.1

**Comment by getNotif** [comment]
I'm having the same issue as well.

**Comment by msavin** [comment]
Ok - I _hope_ its fixed. Please add/remove to try again :8ball:

**Comment by patrickml** [comment]
@msavin is there a new version number other than 2.0.0 that we need to use?

**Comment by rcarter** [comment]
working here :)

**Comment by aminecmi** [comment]
seems to work. thanks.

**Comment by msavin** [comment]
Great! 

@patrickml nope, because I pushed up one of the dependencies as a minor update. When you remove/add, it then grabs the latest one. Good read here: http://semver.org/

**Comment by johnschult** [comment]
Works for me :+1:

**Comment by aminecmi** [comment]
Ok, responded too fast.

That fixed the problem, but I'm now having issues using meteor toys.

Here is the console output: [image](http://i.imgur.com/ci3R4LM.png)

**Comment by patrickml** [comment]
@msavin its working now

**Comment by purplecones** [comment]
Not sure why it still fails when I add it. Heres the output:

```
Changes to your project's package version selections:

dburles:mongo-collection-instances  added, version 0.3.4
gwendall:body-events                added, version 0.1.6
lai:collection-extensions           added, version 0.1.4
meteortoys:allthings                added, version 2.0.0
meteortoys:authenticate             added, version 1.0.0
meteortoys:autopub                  added, version 1.0.0
meteortoys:blueprint                added, version 1.0.0
meteortoys:email                    added, version 1.0.0
meteortoys:hotreload                added, version 1.0.0
meteortoys:listen                   added, version 1.0.0
meteortoys:method                   added, version 1.0.0
meteortoys:pro                      added, version 1.0.0
meteortoys:pub                      added, version 1.0.0
meteortoys:result                   added, version 1.0.0
meteortoys:shell                    added, version 1.0.0
meteortoys:status                   added, version 1.0.0
meteortoys:sub                      added, version 1.0.0
meteortoys:throttle                 added, version 1.0.0
meteortoys:toykit                   added, version 1.0.2
meteortoys:toypro                   added, version 1.0.0
msavin:jetsetter                    added, version 1.1.0
msavin:mongol                       added, version 1.2.0

W20151002-14:41:07.757(-4)? (STDERR)
W20151002-14:41:07.761(-4)? (STDERR) /Users/purplecones/.meteor/packages/meteor-tool/.1.1.9.1npsexx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20151002-14:41:07.762(-4)? (STDERR)                        throw(ex);
W20151002-14:41:07.762(-4)? (STDERR)                              ^
W20151002-14:41:07.762(-4)? (STDERR) TypeError: Property 'undefined' of object [object Object] is not a function
W20151002-14:41:07.763(-4)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:290:1)
W20151002-14:41:07.763(-4)? (STDERR)     at Package (packages/meteortoys_toykit/packages/meteortoys_toykit.js:293:1)
W20151002-14:41:07.763(-4)? (STDERR)     at /Users/purplecones/Projects/myProject/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:325:4
W20151002-14:41:07.763(-4)? (STDERR)     at /Users/purplecones/Projects/myProject/.meteor/local/build/programs/server/packages/meteortoys_toykit.js:334:3
W20151002-14:41:07.763(-4)? (STDERR)     at /Users/purplecones/Projects/myProject/.meteor/local/build/programs/server/boot.js:242:10
W20151002-14:41:07.764(-4)? (STDERR)     at Array.forEach (native)
W20151002-14:41:07.764(-4)? (STDERR)     at Function._.each._.forEach (/Users/purplecones/.meteor/packages/meteor-tool/.1.1.9.1npsexx++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20151002-14:41:07.764(-4)? (STDERR)     at /Users/purplecones/Projects/myProject/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
```

**Comment by purplecones** [comment]
Strange, its working now o_O

**Comment by agad** [comment]
Working for me.

**Comment by came** [comment]
I was happy all day long :)
Now, I get this out of the blue: (remove meteortoys:allthings solved the issue)

BR, Carsten

Error: Meteor[p] is not a function
TypeError: Meteor[p] is not a function
    at http://localhost:3000/packages/meteortoys_toykit.js?8fa55e766a8eceff60a0dc53c5cc9a5d1e2d7ff9:529:6776
    at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:36)
    at new Tracker.Computation (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:10)
    at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11)
    at http://localhost:3000/packages/meteortoys_toykit.js?8fa55e766a8eceff60a0dc53c5cc9a5d1e2d7ff9:529:6620
    at runStartupCallbacks (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:785:22)
    at HTMLDocument.ready (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:787:3)

> Before: 7279ms (diff: 7279ms)
>     at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:791:12
>     at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:833:4
>     at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:1086:3
> Error: v8a[L] is not a function
> TypeError: v8a[L] is not a function
>     at http://localhost:3000/packages/meteortoys_toykit.js?8fa55e766a8eceff60a0dc53c5cc9a5d1e2d7ff9:529:7961
>     at runStartupCallbacks (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:785:22)
>     at ready (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:787:3)
> 
> Before: 7648ms (diff: 7648ms)
>     at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:798:10
>     at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:833:4
>     at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:1086:3

**Comment by purplecones** [comment]
Same here, also removed until issue is resolved. It came out of nowhere.

On Oct 3, 2015, at 8:23 PM, Carsten Meyer notifications@github.com wrote:

I was happy all day long :)
Now, I get this out of the blue: (remove meteortoys:allthings solved the issue)

BR, Carsten

Error: Meteor[p] is not a function
TypeError: Meteor[p] is not a function
at http://localhost:3000/packages/meteortoys_toykit.js?8fa55e766a8eceff60a0dc53c5cc9a5d1e2d7ff9:529:6776
at Tracker.Computation._compute (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:327:36)
at new Tracker.Computation (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:243:10)
at Object.Tracker.autorun (http://localhost:3000/packages/tracker.js?6d0890939291d9780f7e2607ee3af3e7f98a3d9c:566:11)
at http://localhost:3000/packages/meteortoys_toykit.js?8fa55e766a8eceff60a0dc53c5cc9a5d1e2d7ff9:529:6620
at runStartupCallbacks (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:785:22)
at HTMLDocument.ready (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:787:3)

Before: 7279ms (diff: 7279ms)
at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:791:12
at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:833:4
at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:1086:3
Error: v8a[L] is not a function
TypeError: v8a[L] is not a function
at http://localhost:3000/packages/meteortoys_toykit.js?8fa55e766a8eceff60a0dc53c5cc9a5d1e2d7ff9:529:7961
at runStartupCallbacks (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:785:22)
at ready (http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:787:3)

Before: 7648ms (diff: 7648ms)
at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:798:10
at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:833:4
at http://localhost:3000/packages/meteor.js?43b7958c1598803e94014f27f5f622b0bddc0aaf:1086:3

**Comment by rcarter** [comment]
yup. same here :(

**Comment by msavin** [comment]
Lol the madness continues. Any chance you guys had Throttle enabled?

**Comment by rcarter** [comment]
not here. I just did a remove/add of meteortoys:allthings and it gives me this client side:

<img width="432" alt="screen shot 2015-10-03 at 8 40 26 pm" src="https://cloud.githubusercontent.com/assets/19660/10265870/0df73c04-6a0f-11e5-81f2-ca37f097fd6b.png">

**Comment by jamielob** [comment]
Just got the same messages as @rcarter shows above also.   No throttle enabled.

**Comment by came** [comment]
I did not throttle but I installed meteortoys:notifications

2015-10-04 2:42 GMT+02:00 Jamie Loberman notifications@github.com:

> Just got the same messages as @rcarter https://github.com/rcarter shows
> above also. No throttle enabled.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MeteorToys/allthings/issues/41#issuecomment-145303336
> .

## 

Carsten Meyer

Stuttgarter Platz 1a
10627 Berlin

M: 0176 24631236
Skype: meyer.carsten

**Comment by getNotif** [comment]
Worked for me for most of the day too and now I have the same TypeErrors.

**Comment by ghost** [comment]
+1
`Meteor[p] is not a function`
`v8a[L] is not a function`

**Comment by agad** [comment]
+1 here as well.  I was doing heavy development all day and then suddenly
this error popped up.  Everything had been going smoothly before that.  I
DID have throttling on at some point but turned if off (great feature by
the way).

On Sun, Oct 4, 2015 at 6:35 AM, Krabaul notifications@github.com wrote:

> +1
> Meteor[p] is not a function
> v8a[L] is not a function
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MeteorToys/allthings/issues/41#issuecomment-145335803
> .

## 

# 

Alex Gadea - President - Leaf Level Labs, Inc. | www.leaflevellabs.com

**Comment by praneybehl** [comment]
Yep same here 

![image](https://cloud.githubusercontent.com/assets/2144887/10268096/774bc77a-6af9-11e5-9b08-3ca8214ec6ce.png)

**Comment by afareed007** [comment]
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' http://_.googleapis.com https://_.googleapis.com http://_.gstatic.com https://_.gstatic.com http://_.bootstrapcdn.com https://_.bootstrapcdn.com".

msavin_mongol.js:44 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
msavin_jetsetter.js:62 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_blueprint.js:118 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_authenticate.js:99 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_method.js:148 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_result.js:123 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_autopub.js:75 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_pub.js:140 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_sub.js:179 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_email.js:77 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_listen.js:124 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_throttle.js:76 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_status.js:88 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_hotreload.js:76 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined
meteortoys_toypro.js:797 Uncaught TypeError: Cannot read property 'MeteorToysDict' of undefined

**Comment by Taik** [comment]
+1 same error:

```
Meteor[p] is not a function
v8a[L] is not a function
```

**Comment by msavin** [comment]
New update pushed with another patch.. looks to be working. Please try again. Hopefully this doesn't break by tomorrow. 

EDIT: Also, apologies for the breaking!

**Comment by msavin** [comment]
To repair, remove Meteor Toys then run meteor add meteortoys:allthings@2.0.0

**Comment by msavin** [comment]
@ahmadthd regarding the eval() error, it looks like you have browser policy package or some kind of security feature blocking eval(). The next Meteor Toys release (2.1) drops eval(), but I'm holding off on the release as it'll be Meteor 1.2-only, and I want to make sure this works from 1.0 up.

**Comment by jamielob** [comment]
Thanks @msavin! Working again.  I went back to using MongoInspector for a day :)

**Comment by Anima-t3d** [comment]
So far so good... Thanks!

**Comment by afareed007** [comment]
thanks @msavin.

**Comment by praneybehl** [comment]
I'm now getting this issue: https://github.com/MeteorToys/allthings/issues/45

**Comment by msavin** [comment]
@jamielob haha that's old school!

Closing this issue as its been solved
